export type category =
    | "Acessórios"
    | "Calçados"
    | "Bermudas"
    | "Calças Alfaiataria"
    | "Blazer"
    | "T-Shirts"
    | "Calças Jeans"
    | "Blusas Sociais"
    | "Moda Casual"
    | "Moda Corporativa"
    | "Livros"
    | "Camisas"
    | "Nova colecao"
    | "";
